In [1]:
import numpy as np
import pandas as pd
np.random.seed(100)

In [2]:
input_data = pd.read_csv('/Users/shailendrapatil/Spring 2017/ML/Assignments/Extra Credit Programming/traning_data.csv', delimiter=',')

# Taking the output
desired_output = input_data.iloc[:,4:5]

# Separating the input
input_data = input_data.iloc[:, :4] 

#Converting to numpy array as matrix multiplication is easier in numpy
input_data = np.array(input_data)
desired_output = np.array(desired_output)

#Adding bias input
bias_input = np.ones(len(input_data))
input_data = np.insert(input_data,0,bias_input,axis =1)

momentum = 0

In [3]:
class Neural_networks(object):
    def __init__(self):
        np.random.seed(100)
        #Initializing
        self.inputLayerSize = 4
        self.outputLayerSize =1
        self.hiddenLayerSize = 4
        
        
        #Initializing the weights
        self.W1 = np.random.uniform(-1,1,(self.inputLayerSize+1,self.hiddenLayerSize))
        self.W2 = np.random.uniform(-1,1,(self.hiddenLayerSize,self.outputLayerSize))
        self.bias =np.random.uniform(-1,1,self.outputLayerSize)
        print "Initialized W1 for above learning rate : ", self.W1
        print "Intialized W2 for above learning rate : ", self.W2

#Code for forward feed
    def forward_feed(self,X):
        #z2 is the input to th hidden layer units
        self.z2 = np.dot(X,self.W1)
        
        #a2 is the output of hidden layer units
        self.a2 = self.sigmoid(self.z2)
        
        #z3 is the input to the output layer
        self.z3 = np.dot(self.a2,self.W2)

        #Output
        self.yhat = self.sigmoid(self.z3)
        return  self.yhat
        
    def sigmoid(self,z):
        return 1/(1+np.exp(-z))
    
    def sigmoid_derivative(self,z):
        return (np.exp(-z)/((1+np.exp(-z))**2))
    
    def error_function(self,X,y):
        self.yhat = self.forward_feed(X)
        return np.abs((y - self.yhat))
    
    def gradient_function(self,X,y):
        error = self.error_function(X,y)
        if(sum(error<0.05)==len(X)):
            print "Final W1 : ", self.W1
            print "Final W2 : ", self.W2
            return sum(error<0.05)
        else:         
            self.delta3 = np.multiply(-(y-self.yhat),self.sigmoid_derivative(self.z3))#+self.bias))
            self.gradient_wrt_W2 = np.dot(self.a2.T,self.delta3)
            delta2 = np.dot(self.delta3,self.W2.T)*self.sigmoid_derivative(self.z2)
            self.gradient_wrt_W1 = np.dot(X.T,delta2)
            self.update_weight()
            return sum(error<0.05)
        
    def update_weight(self):
        self.W1 = self.W1 - ((learning_rate)/(1-momentum)) * self.gradient_wrt_W1
        self.W2 = self.W2 - ((learning_rate)/(1-momentum)) * self.gradient_wrt_W2



In [4]:
learning_rate = 0.05
No_of_epochs={}
Final_output = {}

while(learning_rate<=0.5):
    print "Learning rate: ",learning_rate
    neural_network = Neural_networks()
    i=0
    Error_count = 0
    while(Error_count!=len(input_data)):
        i = i+1
#        print "Epoch: ",i
        Error_count = neural_network.gradient_function(input_data,desired_output)
        if(i>500000):
            break
    No_of_epochs[learning_rate]=i
    Final_output[learning_rate] = neural_network.yhat
    print "Yhat for learning_rate = ",learning_rate,"is :",neural_network.yhat
    print "Absolute error for learning_rate = ",learning_rate,"is: ",np.abs(neural_network.yhat-desired_output)
    learning_rate+=0.05
    Error_count = 0

Learning rate:  0.05
Initialized W1 for above learning rate :  [[ 0.08680988 -0.44326123 -0.15096482  0.68955226]
 [-0.99056229 -0.75686176  0.34149817  0.65170551]
 [-0.72658682  0.15018666  0.78264391 -0.58159576]
 [-0.62934356 -0.78324622 -0.56060501  0.95724757]
 [ 0.6233663  -0.65611797  0.6324495  -0.45185251]]
Intialized W2 for above learning rate :  [[-0.13659163]
 [ 0.88005964]
 [ 0.63529876]
 [-0.3277761 ]]
Final W1 :  [[ 3.08804523  3.3692949  -6.40732613  1.91982866]
 [-8.29458768 -2.08042579  1.88638647  7.47145221]
 [-7.62767624 -5.13205729  3.87435426 -5.64654901]
 [-8.28296229 -2.07988353  1.88619562  7.46893827]
 [ 8.27477797  2.07424457 -1.92300814 -7.56895356]]
Final W2 :  [[-13.15691487]
 [ 16.60945528]
 [ 15.88700076]
 [ -9.42032172]]
Yhat for learning_rate =  0.05 is : [[ 0.00887291]
 [ 0.966169  ]
 [ 0.97590732]
 [ 0.00989039]
 [ 0.96234416]
 [ 0.04393018]
 [ 0.03251345]
 [ 0.96127227]
 [ 0.97589177]
 [ 0.0099231 ]
 [ 0.04009434]
 [ 0.97538458]
 [ 0.03251233]
 [ 